name: Build and Push
on:
  push:
    branches:
      - release/v[0-9]+.[0-9]+

env:
  REPORT_FILE: trivy-report.txt
  SLACK_CHANNEL: test-submission
  NAME: Ji Jia

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan vulnerability with Trivy
        id: scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          output: ${{ env.REPORT_FILE }}
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
      - name: Notify scan failure
        if: steps.scan.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: {{ env.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FILE_UPLOAD: ${{ env.REPORT_FILE }}
          SLACK_TITLE: Scan failed - ${{ env.NAME }}
          SLACK_MESSAGE: Trivy scan failed, see uploaded report please
        
  
