name: Build and Push
on:
  push:
    branches:
      - release/v[0-9]+.[0-9]+

env:
  REPORT_FILE: trivy-report.txt
  SLACK_CHANNEL: submission
  NAME: Ji Jia
  IMAGE_NAME: cicd

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan vulnerability with Trivy
        id: scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          output: ${{ env.REPORT_FILE }}
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
      - name: Notify scan failure
        if: steps.scan.outcome == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ env.SLACK_CHANNEL }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FILE_UPLOAD: ${{ env.REPORT_FILE }}
          SLACK_TITLE: Scan failed - ${{ env.NAME }}
          SLACK_MESSAGE: Trivy scan failed, see uploaded report
      - name: Fail this run
        if: steps.scan.outcome == 'failure'
        run: exit 1

  build-and-sign:
    name: Build and sign
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - name: Sign the image with cosign
        run: |
          cosign sign --key env://COSIGN_PRIVATE_KEY --yes ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          DIGEST: ${{ steps.build-push.outputs.digest }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      - name: Notify success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Image build and signed
          SLACK_MESSAGE: "*Name:* ${{ env.NAME }}\n*Matriculation:* ${{ secrets.MATRICULATION }}\n*Email:* ${{ secrets.EMAIL }}\n*Git:* ${{ github.server_url }}/${{ github.repository }} \n*Image:* https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

        
  
